### ISSUE TITLE
throws an error libtoolize not found

### ISSUE THREAD

**Issue by asheesh-bless** [xkjyeah/ibus-unicode-db#1]
While running the script ./autogen.sh . it throws an error that libtoolize not found.  I tried to download it but could not found the packaeg.

**Comment by xkjyeah** [comment]
Hi I have not updated this package in ages or tested it against the latest
versions of GNOME desktop and friends.

Try installing the packages mentioned in
https://github.com/beakerbrowser/beaker/issues/54. Thank you for your
interest and support!

Feel free to fork the project if you want to make any changes
